FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow pysqlite3

EXPOSE 5000

ENV BACKEND_URI=sqlite:///mlflow.db
ENV DEFAULT_ARTIFACT_ROOT=/app/mlruns

RUN mkdir -p /app/mlruns

CMD mlflow server \
    --backend-store-uri ${BACKEND_URI} \
    --default-artifact-root ${DEFAULT_ARTIFACT_ROOT} \
    --host 0.0.0.0 \
    --port 5000
